#!/bin/bash
# Test script for Lab 6 - restore_branch_from_dwh procedure
# Executes: ALTER TABLE (GENERATED BY DEFAULT), reload procedure, clear branch, restore one date, verify results

set -e

echo "=== Lab 6 Test: Restore Branch from DWH ==="
echo ""

echo "1. Altering branch_west identity columns to GENERATED BY DEFAULT..."
docker compose exec -T db psql -U postgres -d branch_west -c "ALTER TABLE customer ALTER COLUMN customer_id SET GENERATED BY DEFAULT; ALTER TABLE product ALTER COLUMN product_id SET GENERATED BY DEFAULT; ALTER TABLE category ALTER COLUMN category_id SET GENERATED BY DEFAULT; ALTER TABLE sale ALTER COLUMN sale_id SET GENERATED BY DEFAULT; ALTER TABLE sale_item ALTER COLUMN sale_item_id SET GENERATED BY DEFAULT;" && echo "✓ branch_west altered"

echo ""
echo "2. Altering branch_east identity columns to GENERATED BY DEFAULT..."
docker compose exec -T db psql -U postgres -d branch_east -c "ALTER TABLE customer ALTER COLUMN customer_id SET GENERATED BY DEFAULT; ALTER TABLE product ALTER COLUMN product_id SET GENERATED BY DEFAULT; ALTER TABLE category ALTER COLUMN category_id SET GENERATED BY DEFAULT; ALTER TABLE sale ALTER COLUMN sale_id SET GENERATED BY DEFAULT; ALTER TABLE sale_item ALTER COLUMN sale_item_id SET GENERATED BY DEFAULT;" && echo "✓ branch_east altered"

echo ""
echo "3. Reloading procedure..."
docker compose exec -T db psql -U postgres -d dwh -f /docker/sql/60_restore_branch_from_dwh.sql && echo "✓ Procedure reloaded"

echo ""
echo "4. Ensuring pgcrypto extension..."
docker compose exec -T db psql -U postgres -d dwh -c "CREATE EXTENSION IF NOT EXISTS pgcrypto;" && echo "✓ pgcrypto ready"

echo ""
echo "5. Clearing branch_west tables..."
docker compose exec -T db psql -U postgres -d branch_west -c "TRUNCATE sale_item, sale, product_category, product, category, customer RESTART IDENTITY;" && echo "✓ branch_west cleared"

echo ""
echo "6. Calling restore_branch_from_dwh for branch west, date 2025-06-23..."
docker compose exec -T db psql -U postgres -d dwh -c "CALL restore_branch_from_dwh('west'::text, '2025-06-23'::date, '2025-06-23'::date, true::boolean);" && echo "✓ Restore completed"

echo ""
echo "7. Checking restored row counts in branch_west..."
docker compose exec -T db psql -U postgres -d branch_west -c "SELECT (SELECT COUNT(*) FROM customer) AS customers, (SELECT COUNT(*) FROM product) AS products, (SELECT COUNT(*) FROM sale) AS sales, (SELECT COUNT(*) FROM sale_item) AS sale_items;"

echo ""
echo "8. Checking restore_log entries..."
docker compose exec -T db psql -U postgres -d dwh -c "SELECT * FROM dwh.restore_log ORDER BY id DESC LIMIT 5;"

echo ""
echo "=== Test Complete ==="

