-- /docker/sql/60_restore_branch_from_dwh.sql (v2)
-- Procedure to restore branch data from the DWH to a branch using postgres_fdw foreign tables.
-- IMPORTANT:
-- 1) This procedure assumes the target branch tables are EMPTY (unless p_force=true).
-- 2) Because postgres_fdw foreign tables do NOT carry identity/default metadata, we MUST insert explicit PK values.
-- 3) For this to work, branch tables' identity columns must be GENERATED BY DEFAULT (not ALWAYS).

CREATE TABLE IF NOT EXISTS dwh.restore_log (
  id SERIAL PRIMARY KEY,
  branch_code TEXT NOT NULL,
  start_date DATE NOT NULL,
  end_date DATE NOT NULL,
  customers_inserted INT,
  products_inserted INT,
  categories_inserted INT,
  sales_inserted INT,
  sale_items_inserted INT,
  run_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE OR REPLACE PROCEDURE restore_branch_from_dwh(
    p_branch_code TEXT,
    p_start_date  DATE,
    p_end_date    DATE,
    p_force       BOOLEAN DEFAULT false
)
LANGUAGE plpgsql
AS $$
DECLARE
    v_branch_key BIGINT;
    v_count INT;
    v_target_schema TEXT;

    rec RECORD;

    v_customers INT := 0;
    v_products INT := 0;
    v_categories INT := 0;
    v_sales INT := 0;
    v_sale_items INT := 0;
BEGIN
    IF p_start_date IS NULL OR p_end_date IS NULL OR p_start_date > p_end_date THEN
        RAISE EXCEPTION 'Invalid date range: % - %', p_start_date, p_end_date;
    END IF;

    SELECT branch_key INTO v_branch_key
    FROM dwh.dim_branch
    WHERE branch_code = p_branch_code;

    IF NOT FOUND THEN
        RAISE EXCEPTION 'Branch % not found in dwh.dim_branch', p_branch_code;
    END IF;

    v_target_schema := 'src_' || p_branch_code;

    SELECT COUNT(*) INTO v_count
    FROM dwh.fact_sale_item f
    JOIN dwh.dim_date dd ON f.date_key = dd.date_key
    WHERE f.branch_key = v_branch_key
      AND dd.full_date BETWEEN p_start_date AND p_end_date;

    IF v_count = 0 THEN
        RAISE EXCEPTION 'No fact records found in dwh for branch % in date range % - %', p_branch_code, p_start_date, p_end_date;
    END IF;

    IF NOT p_force THEN
        BEGIN
            EXECUTE format('SELECT 1 FROM %I.customer LIMIT 1', v_target_schema) INTO v_count;
            IF v_count IS NOT NULL THEN
                RAISE EXCEPTION 'Target branch tables are not empty (found rows in customer). TRUNCATE branch tables first, or use p_force=true (not recommended).';
            END IF;
        EXCEPTION WHEN OTHERS THEN
            NULL;
        END;
    ELSE
        RAISE NOTICE 'p_force=true: skipping emptiness checks for target tables';
    END IF;

    ------------------------------
    -- 1) Customers used in range
    ------------------------------
    FOR rec IN
      SELECT DISTINCT dc.customer_id, dc.customer_name
      FROM dwh.dim_customer dc
      JOIN dwh.fact_sale_item f ON f.customer_key = dc.customer_key
      JOIN dwh.dim_date dd ON f.date_key = dd.date_key
      WHERE dc.branch_key = v_branch_key
        AND dd.full_date BETWEEN p_start_date AND p_end_date
      ORDER BY dc.customer_id
    LOOP
        EXECUTE format(
          'INSERT INTO %I.customer (customer_id, customer_name, rowguid, modifieddate)
           VALUES ($1,$2,$3,$4)',
          v_target_schema
        )
        USING rec.customer_id, rec.customer_name, gen_random_uuid(), NOW();

        v_customers := v_customers + 1;
    END LOOP;

    ------------------------------
    -- 2) Products used in range
    ------------------------------
    FOR rec IN
      SELECT DISTINCT dp.product_id, dp.product_name, dp.list_price
      FROM dwh.dim_product dp
      JOIN dwh.fact_sale_item f ON f.product_key = dp.product_key
      JOIN dwh.dim_date dd ON f.date_key = dd.date_key
      WHERE dp.branch_key = v_branch_key
        AND dd.full_date BETWEEN p_start_date AND p_end_date
      ORDER BY dp.product_id
    LOOP
        EXECUTE format(
          'INSERT INTO %I.product (product_id, product_name, list_price, rowguid, modifieddate)
           VALUES ($1,$2,$3,$4,$5)',
          v_target_schema
        )
        USING rec.product_id, rec.product_name, rec.list_price, gen_random_uuid(), NOW();

        v_products := v_products + 1;
    END LOOP;

    ------------------------------
    -- 3) Categories for those products
    ------------------------------
    FOR rec IN
      WITH used_products AS (
        SELECT DISTINCT f.product_key
        FROM dwh.fact_sale_item f
        JOIN dwh.dim_date dd ON f.date_key = dd.date_key
        WHERE f.branch_key = v_branch_key
          AND dd.full_date BETWEEN p_start_date AND p_end_date
      )
      SELECT DISTINCT dcat.category_id, dcat.category_name
      FROM used_products up
      JOIN dwh.bridge_product_category bc ON bc.product_key = up.product_key
      JOIN dwh.dim_category dcat ON dcat.category_key = bc.category_key
      JOIN dwh.dim_product dp ON dp.product_key = up.product_key
      WHERE dcat.branch_key = v_branch_key AND dp.branch_key = v_branch_key
      ORDER BY dcat.category_id
    LOOP
        EXECUTE format(
          'INSERT INTO %I.category (category_id, category_name, rowguid, modifieddate)
           VALUES ($1,$2,$3,$4)',
          v_target_schema
        )
        USING rec.category_id, rec.category_name, gen_random_uuid(), NOW();

        v_categories := v_categories + 1;
    END LOOP;

    ------------------------------
    -- 4) product_category relationships
    ------------------------------
    FOR rec IN
      WITH used_products AS (
        SELECT DISTINCT f.product_key
        FROM dwh.fact_sale_item f
        JOIN dwh.dim_date dd ON f.date_key = dd.date_key
        WHERE f.branch_key = v_branch_key
          AND dd.full_date BETWEEN p_start_date AND p_end_date
      )
      SELECT DISTINCT dp.product_id, dcat.category_id
      FROM used_products up
      JOIN dwh.bridge_product_category bc ON bc.product_key = up.product_key
      JOIN dwh.dim_product dp ON dp.product_key = bc.product_key
      JOIN dwh.dim_category dcat ON dcat.category_key = bc.category_key
      WHERE dp.branch_key = v_branch_key AND dcat.branch_key = v_branch_key
      ORDER BY dp.product_id, dcat.category_id
    LOOP
        EXECUTE format(
          'INSERT INTO %I.product_category (product_id, category_id, rowguid, modifieddate)
           VALUES ($1,$2,$3,$4)',
          v_target_schema
        )
        USING rec.product_id, rec.category_id, gen_random_uuid(), NOW();
    END LOOP;

    ------------------------------
    -- 5) Sales (headers) in range
    ------------------------------
    FOR rec IN
      SELECT
        f.sale_id,
        dd.full_date AS sale_date,
        dc.customer_id,
        SUM(f.line_amount) AS total_amount
      FROM dwh.fact_sale_item f
      JOIN dwh.dim_date dd ON f.date_key = dd.date_key
      JOIN dwh.dim_customer dc ON f.customer_key = dc.customer_key
      WHERE f.branch_key = v_branch_key
        AND dd.full_date BETWEEN p_start_date AND p_end_date
      GROUP BY f.sale_id, dd.full_date, dc.customer_id
      ORDER BY dd.full_date, f.sale_id
    LOOP
        EXECUTE format(
          'INSERT INTO %I.sale (sale_id, customer_id, sale_date, total_amount, rowguid, modifieddate)
           VALUES ($1,$2,$3,$4,$5,$6)',
          v_target_schema
        )
        USING rec.sale_id, rec.customer_id, rec.sale_date, rec.total_amount, gen_random_uuid(), NOW();

        v_sales := v_sales + 1;
    END LOOP;

    ------------------------------
    -- 6) Sale items in range
    ------------------------------
    FOR rec IN
      SELECT
        f.sale_item_id,
        f.sale_id,
        dp.product_id,
        f.quantity,
        f.unit_price,
        f.line_amount
      FROM dwh.fact_sale_item f
      JOIN dwh.dim_date dd ON f.date_key = dd.date_key
      JOIN dwh.dim_product dp ON f.product_key = dp.product_key
      WHERE f.branch_key = v_branch_key
        AND dd.full_date BETWEEN p_start_date AND p_end_date
      ORDER BY f.sale_id, f.sale_item_id
    LOOP
        EXECUTE format(
          'INSERT INTO %I.sale_item (sale_item_id, sale_id, product_id, quantity, unit_price, line_amount, rowguid, modifieddate)
           VALUES ($1,$2,$3,$4,$5,$6,$7,$8)',
          v_target_schema
        )
        USING rec.sale_item_id, rec.sale_id, rec.product_id, rec.quantity, rec.unit_price, rec.line_amount, gen_random_uuid(), NOW();

        v_sale_items := v_sale_items + 1;
    END LOOP;

    INSERT INTO dwh.restore_log(branch_code, start_date, end_date,
                               customers_inserted, products_inserted, categories_inserted,
                               sales_inserted, sale_items_inserted)
    VALUES (p_branch_code, p_start_date, p_end_date,
            v_customers, v_products, v_categories, v_sales, v_sale_items);

    RAISE NOTICE 'Restore completed for branch % between % and % (target schema: %). Inserted rows: customers=% products=% categories=% sales=% sale_items=%',
        p_branch_code, p_start_date, p_end_date, v_target_schema, v_customers, v_products, v_categories, v_sales, v_sale_items;
END;
$$;
